name: Build
 
on:
  push:
    branches: [ main ]

jobs:
  relay:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: actions/cache@v2
         with:
           path: node_modules
           key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-npm-
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - name: Install Dependencies
         run: npm install
       - name: Run Relay Compiler
         run: npm run validate-relay
         
  lint:
    runs-on: ubuntu-latest
    needs: [relay]

    steps:
       - uses: actions/checkout@v2
       - uses: actions/cache@v2
         with:
           path: node_modules
           key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-npm-
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - name: Install Dependencies
         run: npm install
       - name: Run Linter
         run: npm run lint
       
  deploy:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
       - uses: actions/checkout@v2
       - uses: actions/cache@v2
         with:
           path: node_modules
           key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-npm-
       - uses: actions/setup-node@v2
         with:
           node-version: '14'
       - name: Install Dependencies
         run: npm install
       - name: Build for Production
         run: npm run build
         env:
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
       - name: Prepare Release Folder
         run: |
          mkdir release
          cp -a build release/build
          cp static.json release/static.json
          cp .buildpacks release/.buildpacks
       - name: Add known host file
         run: echo "78.47.176.210 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNgbL1ikZ0maqh9bNW7tRCdPyAfh+SiAvE/cYqBsPCsqV4+k3sHg3iASi5ywriNqZ5IMKa7gfhBudVPxb/fqjdw=" > ./known_hosts
       - name: Push to Dokku
         uses: s0/git-publish-subdir-action@develop
         env:
          SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          REPO: dokku@78.47.176.210:dogtor-frontend
          BRANCH: master
          FOLDER: release
          KNOWN_HOSTS_FILE: known_hosts
          SKIP_EMPTY_COMMITS: true
          SQUASH_HISTORY: true
